### ISSUE TITLE
Add Initial Content

### ISSUE THREAD

**Issue by dorsain** [csctd/profile-website-dorsain#6]
- [ ]  Pictures
- [ ] Different language
- [ ]  Description

**Comment by dorsain** [comment]
![PXL_20230808_195701984](https://github.com/csctd/profile-website-dorsain/assets/141340717/b165681d-115e-4927-a824-e7c4c872b2e1)

**Comment by sarmenti7** [comment]
Nice work! Could you combine any of these pages together to simplify your navigation menu?
