### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by dorsain** [csctd/profile-website-dorsain#7]
- [ ] Simple
- [ ] sleek
- [ ] is colorblind friendly
- [ ] accessible to most

**Comment by dorsain** [comment]
![WIN_20230808_16_09_01_Pro](https://github.com/csctd/profile-website-dorsain/assets/141340717/641978bd-39c9-4100-9aaa-8db1a0c0ca79)

**Comment by sarmenti7** [comment]
Perfect!
